flask/bin/pip3 install flask
flask/bin/pip3 install flask-login
flask/bin/pip3 install flask-openid
flask/bin/pip3 install flask-mail
flask/bin/pip3 install flask-sqlalchemy
flask/bin/pip3 install sqlalchemy-migrate
flask/bin/pip3 install flask-whooshalchemy
flask/bin/pip3 install flask-wtf
flask/bin/pip3 install flask-babel
flask/bin/pip3 install guess_language
flask/bin/pip3 install flipflop
flask/bin/pip3 install coverage
pip3 install requests
